export const cards = [
  // {
  //   cardId: 0,
  //   templateId: 0,
  //   userId: 0,
  //   nickname: "string",
  //   animal: "string",
  //   profileColor: "string",
  //   accessory: "string",
  //   mbti: "string",
  //   hobby: "string",
  //   secretTip: "string",
  //   tmi: "string",
  // },
  {
    cardId: 0,
    templateId: 0,
    userId: 0,
    nickname: "발랄한",
    animal: "고양이",
    profileColor: "4",
    accessory: "string",
    mbti: "INFP",
    hobby: "산책",
    secretTip: "좋은 귀 기울이기",
    tmi: "커피 중독",
  },
  {
    cardId: 1,
    templateId: 0,
    userId: 0,
    nickname: "조용한",
    animal: "개구리",
    profileColor: "1",
    accessory: "",
    mbti: "ISTP",
    hobby: "영화보기",
    secretTip: "책 선물하기",
    tmi: "높이 뛰기 잘함",
  },
  {
    cardId: 2,
    templateId: 0,
    userId: 0,
    nickname: "귀여운",
    animal: "강아지",
    profileColor: "9",
    accessory: "",
    mbti: "ESTJ",
    hobby: "축구",
    secretTip: "매일 운동하기",
    tmi: "밤샘 가능",
  },
  {
    cardId: 3,
    templateId: 0,
    userId: 0,
    nickname: "부드러운",
    animal: "곰",
    profileColor: "3",
    accessory: "",
    mbti: "ESTJ",
    hobby: "축구",
    secretTip: "매일 운동하기",
    tmi: "밤샘 가능",
  },
  {
    cardId: 4,
    templateId: 0,
    userId: 0,
    nickname: "신나는",
    animal: "돼지",
    profileColor: "5",
    accessory: "",
    mbti: "ESTJ",
    hobby: "축구",
    secretTip: "매일 운동하기",
    tmi: "밤샘 가능",
  },
];

export const teamsData = [
  ["칠가이", "팀A", "팀B"],
  ["팀X"],
  [],
  ["팀Y", "팀Z"],
  [],
];

// 현재 팀페이지에서 사용 중인 명함 index 반환
export function findCardIndexByTeam(teamName) {
  return teamsData.findIndex((teamList) => teamList.includes(teamName));
}
